# Data Preprocessing

## Objective

After completing data cleaning, the next step is to preprocess the dataset so it can be used for machine learning.

During the data cleaning stage, the following tasks were completed:

- Converted the `TotalCharges` column from object to numeric.
- Removed rows containing missing values.
- Checked and removed duplicate records.
- Dropped the `customerID` column since it does not contribute to churn prediction.

The preprocessing stage focuses on transforming the cleaned data into a machine-learning-ready format by encoding categorical features, scaling numerical features, and building a reusable preprocessing pipeline.

## Feature Encoding and Data Transformation

Machine learning algorithms require numerical input. Since the dataset contains both categorical and numerical features, different preprocessing techniques are applied based on the type of feature.

- Binary categorical features will be converted using binary mapping.
- Multi-category features will be transformed using One-Hot Encoding.
- Numerical features will be standardized using StandardScaler.

To ensure consistency and avoid data leakage, Scikit-learn's `ColumnTransformer` and `Pipeline` will be used to automate the preprocessing workflow.

In [80]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [81]:
df1 = df.copy()

In [82]:
df1.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [83]:
df1["TotalCharges"] = pd.to_numeric(df1["TotalCharges"], errors="coerce")

In [84]:
df1.info

<bound method DataFrame.info of       customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1
1     5575-GNVDE    Male              0      No         No      34
2     3668-QPYBK    Male              0      No         No       2
3     7795-CFOCW    Male              0      No         No      45
4     9237-HQITU  Female              0      No         No       2
...          ...     ...            ...     ...        ...     ...
7038  6840-RESVB    Male              0     Yes        Yes      24
7039  2234-XADUH  Female              0     Yes        Yes      72
7040  4801-JZAZL  Female              0     Yes        Yes      11
7041  8361-LTMKD    Male              1     Yes         No       4
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...
1             Yes                No             DSL            Yes  ...
2             Yes                No             DSL            Yes  ...
3              No  No phone service             DSL            Yes  ...
4             Yes                No     Fiber optic             No  ...
...           ...               ...             ...            ...  ...
7038          Yes               Yes             DSL            Yes  ...
7039          Yes               Yes     Fiber optic             No  ...
7040           No  No phone service             DSL            Yes  ...
7041          Yes               Yes     Fiber optic             No  ...
7042          Yes                No     Fiber optic            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85
1                  No               Mailed check          56.95       1889.50
2                 Yes               Mailed check          53.85        108.15
3                  No  Bank transfer (automatic)          42.30       1840.75
4                 Yes           Electronic check          70.70        151.65
...               ...                        ...            ...           ...
7038              Yes               Mailed check          84.80       1990.50
7039              Yes    Credit card (automatic)         103.20       7362.90
7040              Yes           Electronic check          29.60        346.45
7041              Yes               Mailed check          74.40        306.60
7042              Yes  Bank transfer (automatic)         105.65       6844.50

      Churn
0        No
1        No
2       Yes
3        No
4       Yes
...     ...
7038     No
7039     No
7040     No
7041    Yes
7042     No

[7043 rows x 21 columns]>

In [85]:
df1.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [86]:
df1[df1["TotalCharges"].isnull()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [87]:
df1["TotalCharges"] = df1["TotalCharges"].fillna(0)

In [88]:
df1.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [89]:
df1.duplicated().sum()

np.int64(0)

In [90]:
df1.drop (["customerID"], axis=1, inplace=True)

| Feature         | Type        | ML Treatment   |
| --------------- | ----------- | -------------- |
| gender          | Binary      | Label Encode   |
| Partner         | Binary      | Label Encode   |
| Dependents      | Binary      | Label Encode   |
| PhoneService    | Binary      | Label Encode   |
| Contract        | Categorical | One-Hot Encode |
| InternetService | Categorical | One-Hot Encode |
| PaymentMethod   | Categorical | One-Hot Encode |
| tenure          | Numerical   | Scaling        |
| MonthlyCharges  | Numerical   | Scaling        |
| TotalCharges    | Numerical   | Scaling        |

In [91]:
categorical_cols = df1.select_dtypes(include="object").columns.tolist()

print(categorical_cols)
print(f"Total categorical columns: {len(categorical_cols)}")

['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn']
Total categorical columns: 16

In [92]:
X = df1.drop("Churn", axis=1)
y = df1["Churn"]

print("Features Shape : ", X.shape)
print("Target Shape : ", y.shape)


binary_features = [
    "gender",
    "partner",
    "Dependents",
    "PhoneService",
    "PaperlessBilling"
]

multi_category_features = [
    "MultipleLines",
    "InternetService",
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies",
    "Contract",
    "PaymentMethod"
]

numerical_features = [
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]

Features Shape :  (7043, 19)
Target Shape :  (7043,)

In [96]:
binary_mapping = {
    "gender": {"Male": 1, "Female": 0},
    "Partner": {"Yes": 1, "No": 0},
    "Dependents": {"Yes": 1, "No": 0},
    "PhoneService": {"Yes": 1, "No": 0},
    "PaperlessBilling": {"Yes": 1, "No": 0},
    "Churn": {"Yes": 1, "No": 0}
}

In [97]:
for column, mapping in binary_mapping.items():
    df1[column] = df1[column].map(mapping)

In [98]:
df1[["gender", "Partner", "Dependents", "PhoneService", "PaperlessBilling", "Churn"]].head()

   gender  Partner  Dependents  PhoneService  PaperlessBilling  Churn
0       0        1           0             0                 1      0
1       1        0           0             1                 0      0
2       1        0           0             1                 1      1
3       1        0           0             0                 0      0
4       0        0           0             1                 1      1

## Train-Test Split

Before applying feature transformations such as One-Hot Encoding and Standard Scaling, the dataset is divided into training and testing sets.

The preprocessing steps are fitted only on the training data and later applied to the testing data. This prevents data leakage, ensuring that the model does not gain information from unseen data during training.

In [ ]:
from sklearn.model_selection import train_test_split

X = df1.drop("Churn", axis=1)
y = df1["Churn"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("training features : ", X_train.shape)
print("testing features : ", X_test.shape)

print("training label : ", y_train.shape)
print("testing label : ", y_test.shape)

training features :  (5634, 19)
testing features :  (1409, 19)
training label :  (5634,)
testing label :  (1409,)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numerical_features
        ),
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            multi_category_features
        )
        
    ],
    remainder="passthrough"
)

### Why use `remainder="passthrough"`?

Binary features have already been converted into numerical values using binary mapping. Since these features do not require further preprocessing, they are passed through unchanged while numerical and multi-category features undergo their respective transformations.

This ensures that no useful features are lost during preprocessing.

In [102]:
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

print('Processed training shape : ', X_train_processed.shape)
print('Processed testing shape : ', X_test_processed.shape)

Processed training shape :  (5634, 40)
Processed testing shape :  (1409, 40)

In [103]:
import joblib
import os

In [104]:
os.makedirs("../artifacts", exist_ok=True)

In [105]:
joblib.dump(preprocessor, "../artifacts/preprocessor.pkl")

['../artifacts/preprocessor.pkl']

In [106]:
joblib.dump(
    (X_train, X_test, y_train, y_test),
    "../artifacts/data_split.pkl"
)

['../artifacts/data_split.pkl']